### ISSUE TITLE
Multiple duplicate lines in CSVs

### ISSUE THREAD

**Issue by AlexeyKruglov** [maxonlinux/ratings-history#1]
In some (all?) CSV files downloaded from ratingshistory.info (which I assume to host code from this repo) there are multiple exactly duplicate lines. For example, `20220515 Moody's Investors Service Financial.csv` has 9674 lines, but after removing duplicate lines with `uniq` utility it has only 37 lines. For `20220601 Standard & Poor's Ratings Services Corporate.csv` the numbers are 8924 original and 219 after deduplication.

This looks like a bug in parsing, but I don't have the source XBRL files to check.

Thanks for your effort.

**Comment by maxonlinux** [comment]
Thank you for pointing this out; I appreciate your feedback! I'll definitely look into fixing this issue asap.

**Comment by maxonlinux** [comment]
> This looks like a bug in parsing, but I don't have the source XBRL files to check.

I do have some of the source XML files back from 2022. If you find them useful I can share them with you.

**Comment by maxonlinux** [comment]
Fixed in the `dev` branch (commit [1e9ae37](https://github.com/maxonlinux/ratings-history/commit/1e9ae37b270376626c52716550951d8e5bbfe3c4))
